import { createContext } from 'react';

const PlantInfoContext = createContext({
    plant_id: '',
    common_name: '',
    scientific_name: '',
    family_common_name: '',
    duration: '',
    precipitation_max: '',
    precipitation_min: '',
    native_status: '',
    growth_habit: '',
    drought_tolerance: '',
    foliage_color: '',
    lifespan: '',
    mature_height: '',
    shade_tolerance: '',
    fruit_seed_color: '',
    bloom_period: '',
    growth_period: '',
    flower_color: '',
    saved_common_name: '',
    saved_scientific_name: '',
    saved_family_common_name: '',
    saved_duration: '',
    saved_precipitation_max: '',
    saved_precipitation_min: '',
    saved_specifications: '',
    saved_native_status: '',
    saved_growth_habit: '',
    saved_drought_tolerance: '',
    saved_foliage_color: '',
    saved_lifespan: '',
    saved_mature_height: '',
    saved_shade_tolerance: '',
    saved_fruit_seed_color: '',
    saved_bloom_period: '',
    saved_growth_period: '',
    saved_flower_color: '',
    saved_plant_qty: '',
    handlePlantInputchange: () => {},
    handlePlantInfoSearch: () => {},
    handleRenderPlant: () => {},
    handleUpdateSavedPlant: () => {},
    handleRemovePlant: () => {}
});

export default PlantInfoContext;
